services:
  frontend:
    image: ujwala567/ci-cd-project-frontend:latest
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    image: ujwala567/ci-cd-project-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  auth-service:
    image: ujwala567/ci-cd-project-auth:latest
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  user-service:
    image: ujwala567/ci-cd-project-user:latest
    ports:
      - "3003:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  order-service:
    image: ujwala567/ci-cd-project-order:latest
    ports:
      - "3004:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    